# Generated by Django 6.0.3 on 2026-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_author_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ceramics', 'Керамика'), ('candles', 'Свечи'), ('textile', 'Текстиль'), ('jewelry', 'Украшения'), ('wood', 'Дерево'), ('cosmetics', 'Косметика'), ('other', 'Другое')], default='other', max_length=30),
        ),
    ]
